version: 2
sources:
  - name: raw                # ← this is the alias for gz_raw_data
    schema: gz_raw_data      # ← actual dataset name in BigQuery
    tables:
      - name: sales          # ← alias
        identifier: raw_gz_sales  # ← actual table name in BigQuery
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: order_id
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: products_id
            tests:
              - not_null
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: shipment costs
        columns:
          - name: orders_id
            description: orders_id
            tests:
              - not_null
              - unique